### ISSUE TITLE
Links dead on Hackage docs

### ISSUE THREAD

**Issue by t3hmrman** [ChrisCoffey/haskell-opentracing-light#1]
Hey there, thanks for all the hard work!

Links to this repo are broken on the [Hackage docs](https://hackage.haskell.org/package/servant-tracing-0.1.0.0) -- just thought you might want to know.

**Comment by ChrisCoffey** [comment]
Thanks for letting me know! I've fixed the links.

**Comment by t3hmrman** [comment]
@ChrisCoffey No thank you! I got started with `servant-tracing` last night and was able to get up to speed very quickly, thanks for getting the bare minimum released so I could use it!
