### ISSUE TITLE
Problems with running example

### ISSUE THREAD

**Issue by ChShersh** [ChrisCoffey/haskell-opentracing-light#11]
I'm using Zipkin with `haskell-opentracing-light`. But I have problems running executable example. 

I launched `zipkin` with this command:

```
docker run -d -p 9411:9411 openzipkin/zipkin
```

Then I launched `haskell-opentracing-light` with the following command:

```
TRACING_ENDPOINT="http://localhost:9411/zipkin/" TRACING_SERVICE="foo" stack exec servant-tracing-example
```

I can see Zipkin on `localhost:9411`. But webpage content doesn't change. And `servant-tracing-example` have no output. Looks like example hangs or something like that.

Do you have any ideas regarding why I see such behavior?

**Comment by ChrisCoffey** [comment]
Thanks for posting the question @ChShersh. The example app starts up a servant webservice with tracing enabled on a pair of endpoints. To actually publish some messages you need to interact with the webservice using a client app like `curl`. 

I've updated the readme with more detailed instructions on interacting with the service.

**Comment by ChShersh** [comment]
@ChrisCoffey Thanks! That resolves my issue. I was able to launch your example with Zipkin and observe output.
