### ISSUE TITLE
hackage link points to ChrisCoffey/servant-tracing#readme

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ChrisCoffey/haskell-opentracing-light#6]
at least on the cached page on google.  hackage is down atm.

**Comment by ChrisCoffey** [comment]
Thanks for noticing. The cached page is from 4/3/18, so it should be resolved once Hackage comes online again. I'll keep an eye on it to make sure though.

**Comment by ChrisCoffey** [comment]
Now that hackage is back up I confirmed that the correct link is on the readme. Resolving.
